### ISSUE TITLE
Staking status don't shows the good amount of coins

### ISSUE THREAD

**Issue by osef123** [thecrypt0hunter/CoreWallet#7]
![Sans titre](https://user-images.githubusercontent.com/3747761/72943901-92b59e00-3d77-11ea-9aa0-bd06623d4c05.png)

1400 =/= 1150 + 100

In that case, 1150 is the good amount of mature coins. But 150 immature coins are missing.

**Comment by thecrypt0hunter** [comment]
Fix done here, will include in next release:
https://github.com/thecrypt0hunter/CoreWallet/commit/82317ae0681e02f0ff742abda9629449f2e88b87
